services:
  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes: [db_data:/var/lib/mysql]
    ports: ["3307:3306"]
    healthcheck:
      test: ["CMD-SHELL",
             "mariadb-admin ping -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\" --silent \
              || mariadb -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\" -e 'SELECT 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      start_period: 40s         # give MariaDB time to initialize / run upgrades
      retries: 20

  wordpress:
    image: wordpress:6-php8.2-apache
    depends_on: { db: { condition: service_healthy } }
    environment:
      # DB envs
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      # Admin host envs
      ADMIN_HOST: ${ADMIN_HOST:-admin.mycompany.local}
      ADMIN_ORIGIN: ${ADMIN_ORIGIN}
      WORDPRESS_CONFIG_EXTRA: |
        require_once __DIR__ . '/wp-config-extra.php';
    volumes:
      - wp_data:/var/www/html
      - ./backend/wp-content:/var/www/html/wp-content
      - ./logs/wp-debug.log:/var/www/html/wp-content/debug.log
      - ./logs/apache:/var/log/apache2
      - ./backend/wp-config-extra.php:/var/www/html/wp-config-extra.php:ro
      - ./backend/.htaccess:/var/www/html/.htaccess:ro
    ports: ["8080:80"]
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit((int)!@fsockopen(\"127.0.0.1\",80));'"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 30

  wpcli:
    image: wordpress:cli
    depends_on: { wordpress: { condition: service_healthy } }
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
    volumes:
      - wp_data:/var/www/html 
      - ./backend/wp-content:/var/www/html/wp-content
      - ./logs/wp-debug.log:/var/www/html/wp-content/debug.log
      - ./logs/apache:/var/log/apache2

  setup:
    image: wordpress:cli
    depends_on: { wordpress: { condition: service_healthy } }
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      ADMIN_ORIGIN: ${ADMIN_ORIGIN}
      WP_ADMIN_USER: ${WP_ADMIN_USER:-admin}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS:-admin}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL:-admin@example.com}
    volumes:
      # IMPORTANT: same site volume as the wordpress service
      - wp_data:/var/www/html
      # Your content + config (RO where appropriate)
      - ./backend/wp-content:/var/www/html/wp-content
      - ./backend/wp-config-extra.php:/var/www/html/wp-config-extra.php:ro
      # Bootstrap script
      - ./backend/wp-bootstrap.sh:/bootstrap/wp-bootstrap.sh:ro
    command: [ "bash", "-lc", "/bootstrap/wp-bootstrap.sh" ]
    restart: "no"

  adminer:
    image: adminer
    restart: unless-stopped
    ports: ["9091:8080"]

volumes:
  db_data:
  wp_data: